### PR TITLE
fix(lernbueros)/ci: Add substitution info to LBs and rewrite ci/docker with nix

### PR DESCRIPTION
**Pull request by ixhbinphoenix**

### CODE REVIEW

**Comment by ixhbinphoenix** [comment]
Closes #64

**Comment by ixhbinphoenix** [comment]
This breaks login :+1:

**Comment by ixhbinphoenix** [comment]
Can't revert it bc I already upgrade surrealdb to 1.3 and can't downgrade :+1:

**Comment by Sxyntheon** [comment]
💀

**Review by renkertm — APPROVED** [review]

**Pull request merged**
